export default {
  result: true,
  message: 'Product data',
  data: [
    {
      id: 1,
      product_size: '12',
      product_name: 'Banana',
      price: '₹5.00',
      product_image: 'https://image.shutterstock.com/image-vector/banana-healthy-fruit-vector-illustration-260nw-1547888666.jpg',
      product_category_name: 'FRUIT',
    },
    {
      id: 2,
      product_size: '25 GM',
      product_name: 'Fresh Tomato',
      price: '₹5.00',
      product_image: 'https://4.imimg.com/data4/OJ/IB/ANDROID-8994100/product-500x500.jpeg',
      product_category_name: 'VEGETABLES',
    },
    {
      id: 3,
      product_size: '200 GM',
      product_name: 'BLACK PEPPER',
      price: '₹5.00',
      product_image: 'https://5.imimg.com/data5/OD/RJ/MY-42789577/black-pepper-500x500.jpg',
      product_category_name: 'SPICE',
    },
    {
      id: 4,
      product_size: '200 GM',
      product_name: 'Apple',
      price: '₹15.00',
      product_image: 'https://image.shutterstock.com/image-photo/red-apple-fruit-leaf-isolated-260nw-203589940.jpg',
      product_category_name: 'FRUIT',
    },
    {
      id: 25,
      product_size: '1',
      product_name: 'Bread',
      price: '₹45.00',
      product_image: 'https://i.redd.it/fflmw8k7rj631.jpg',
      product_category_name: 'BAKERY',
    },
    {
      id: 5,
      product_size: '100 GM',
      product_name: 'BLACK CARDAMOM',
      price: '₹5.00',
      product_image: 'https://m.media-amazon.com/images/I/51Pt8JbJYrL.jpg',
      product_category_name: 'SPICE',
    },
    {
      id: 6,
      product_size: '88 LB',
      product_name: 'GREEN CARDAMOM (JUMBO)',
      price: '₹5.00',
      product_image: 'https://cdn.shopify.com/s/files/1/1410/1430/products/munnar-green-cardamom-elaichi-8mm-grade-spices.jpg?v=1610143944',
      product_category_name: 'SPICE',
    },
    {
      id: 7,
      product_size: '44 LB',
      product_name: 'GREEN CARDAMOM (JUMBO)',
      price: '₹5.00',
      product_image: 'https://cdn.shopify.com/s/files/1/1410/1430/products/munnar-green-cardamom-elaichi-8mm-grade-spices.jpg?v=1610143944',
      product_category_name: 'SPICE',
    },
    {
      id: 8,
      product_size: '11 LB',
      product_name: 'GREEN CARDAMOM (JUMBO)',
      price: '₹5.00',
      product_image: 'https://cdn.shopify.com/s/files/1/1410/1430/products/munnar-green-cardamom-elaichi-8mm-grade-spices.jpg?v=1610143944',
      product_category_name: 'SPICE',
    },
    {
      id: 9,
      product_size: '200 GM',
      product_name: 'JUMBO CARDOMON',
      price: '₹5.00',
      product_image: 'https://cdn.shopify.com/s/files/1/1410/1430/products/munnar-green-cardamom-elaichi-8mm-grade-spices.jpg?v=1610143944',
      product_category_name: 'SPICE',
    },
    {
      id: 10,
      product_size: '100 GM',
      product_name: 'GREEN CARDAMOM (JUMBO)',
      price: '₹5.00',
      product_image: 'https://cdn.shopify.com/s/files/1/1410/1430/products/munnar-green-cardamom-elaichi-8mm-grade-spices.jpg?v=1610143944',
      product_category_name: 'SPICE',
    },
    {
      id: 11,
      product_size: '100 GM',
      product_name: 'CARDAMOM',
      price: '₹5.00',
      product_image: 'https://cdn.shopify.com/s/files/1/1410/1430/products/munnar-green-cardamom-elaichi-8mm-grade-spices.jpg?v=1610143944',
      product_category_name: 'SPICE',
    },
    {
      id: 12,
      product_size: '88 LB',
      product_name: 'CARDAMOM SEED',
      price: '₹5.00',
      product_image: 'https://cdn.shopify.com/s/files/1/1410/1430/products/munnar-green-cardamom-elaichi-8mm-grade-spices.jpg?v=1610143944',
      product_category_name: 'SPICE',
    },
    {
      id: 13,
      product_size: '100 GM',
      product_name: 'CARDAMOM SEED',
      price: '₹5.00',
      product_image: 'https://cdn.shopify.com/s/files/1/1410/1430/products/munnar-green-cardamom-elaichi-8mm-grade-spices.jpg?v=1610143944',
      product_category_name: 'SPICE',
    },
    {
      id: 14,
      product_size: '55 LB',
      product_name: 'RED CHILI POWDER',
      price: '₹5.00',
      product_image: 'https://cdn.shopify.com/s/files/1/0530/4552/6694/t/6/assets/When_we_think_of_Indian_spices.jpg?v=1616791729',
      product_category_name: 'SPICE',
    },
    {
      id: 15,
      product_size: '4 LB',
      product_name: 'RED CHILI POWDER',
      price: '₹35.00',
      product_image: 'https://cdn.shopify.com/s/files/1/0530/4552/6694/t/6/assets/When_we_think_of_Indian_spices.jpg?v=1616791729',
      product_category_name: 'SPICE',
    },
    {
      id: 16,
      product_size: '200 GM',
      product_name: 'RED CHILI POWDER',
      price: '₹15.00',
      product_image: 'https://cdn.shopify.com/s/files/1/0530/4552/6694/t/6/assets/When_we_think_of_Indian_spices.jpg?v=1616791729',
      product_category_name: 'SPICE',
    },
    {
      id: 17,
      product_size: '400 GM',
      product_name: 'RED CHILI POWDER',
      price: '₹55.00',
      product_image: 'https://cdn.shopify.com/s/files/1/0530/4552/6694/t/6/assets/When_we_think_of_Indian_spices.jpg?v=1616791729',
      product_category_name: 'SPICE',
    },
    {
      id: 18,
      product_size: '200 GM',
      product_name: 'Black Cardomom',
      price: '₹5.00',
      product_image: 'https://m.media-amazon.com/images/I/51Pt8JbJYrL.jpg',
      product_category_name: 'SPICE',
    },
    {
      id: 19,
      product_size: '1',
      product_name: 'Choclates',
      price: '₹15.00',
      product_image: 'https://www.dessertfortwo.com/wp-content/uploads/2017/02/red-wine-chocolate-truffles-4.jpg',
      product_category_name: 'SWEET',
    },
  ],
};
